import "./globals.css";

export const metadata = {
  title: "SubLekh",
  description: "Generated by create next app",
};

import dbConnect from "@/lib/dbconfig";

dbConnect();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
